theonion/bulbs-public-ads-manager

src/manager.js
src/manager.spec.js

Removes code for filtering ad slots by viewport.
This will be obsoleted by the `<bulbs-dfp>` element.

remove filter by viewport code

---

.travis.yml
README.md
karma.conf.js
package.json
src/manager.js
src/manager.spec.js
src/utils.js
src/utils.spec.js

@spra85 @kand @MelizzaP 
This adds some new event handling to our ad slots. 
```js
this.googletag.pubads().addEventListener('slotRenderEnded', adManager.onSlotRenderEnded);
this.googletag.pubads().addEventListener('impressionViewable', adManager.onImpressionViewable);
this.googletag.pubads().addEventListener('slotOnload', adManager.onSlotOnload)
```
(`slotRenderEnded` was already being handled before this PR.)
Of particular interest are the new DOM custom events that we emit on the slot element as dfp goes through its lifecycle:
```js
utils.dispatchEvent(element, 'dfpSlotRenderEnded');
/***/
utils.dispatchEvent(element, 'dfpImpressionViewable');
/***/
utils.dispatchEvent(element, 'dfpSlotOnload');
```
At the present we will be handling these events in `<div is="bulbs-dfp">` to send more …

add custom events to track dfp lifecylce

---

.gitignore
src/ad-units.js

Prevent header slot from automatically refreshing. Will be released in conjunction with theonion/bulbs-elements#181.
**Release Type**: _patch_
No large-scale features, no breaking changes.
**Updates**
1. `header` slot has `refreshDisabled` to prevent it refreshing automatically.

prevent header slot refresh

---

src/ad-units.js
src/manager.js
src/manager.spec.js

Note - This is a breaking change, which will result in a major version bump to 3.x.  This changes the `loadAds` implementation to defer the call to refresh the slot (which actually fetches the new ad) to the bulbs-elements custom bulbs-dfp element when it is about to come into view unless the ad is configured to `eagerLoad`.  These changes need to be paired with the implementation in this bulbs-elements PR (https://github.com/theonion/bulbs-elements/pull/198).  
Test link below:
http://lazy-load-ads.test.clickhole.com

Changes to allow for lazy-loading ads

---

src/ad-units.js

...  and you are unable to listen to the scroll event with iframes inside Facebook instant

Must eager load this because Facebook already lazy loads

---

src/manager.js
src/manager.spec.js

This PR does a few things, namely: 
- Prevents the bulbs-dfp custom element from refreshing an ad slot based on viewport detection when the slot is already in the process of loading from the ad server
- Makes sure that any time a new ads manager is instantiated the correlator on the page is updated
- Makes sure any time ads are triggered to reload on the page, a new correlator is updated as well
This will be a patch release for the current version
Test link: 
http://change-correlator.test.theonion.com/

Improvements to ad loading consistency

---

.gitignore
package.json
src/manager.js
src/manager.spec.js

Don't call render end callbacks and events when ad is empty.
**Release type**: _patch_
No major changes, only a fix.

empty slot fix

---

src/ad-units.js
src/ad-units.spec.js

@jmelvnsn, this should be what you can key off to remove the margin, background, etc. from the header wrapper until the ad has been loaded
Also, looking for additional approvals @kand @collin @shawncook @MelizzaP

Adds a state to the parent wrapper reflective of whether the ad has loaded

---

src/manager.js
src/manager.spec.js

This PR provides an optional flag allowing an integrating site, etc. to force an update of the correlator prior to loading ads

Update correlator option

---

src/ad-units.js
src/ad-units.spec.js
src/manager.js
src/utils.js
src/utils.spec.js

Primary reason for this PR is to remove the dependency on `utils.js` for the `ad-units.js` file, which will allow us to remove that ad-units.js altogether from this repo.
Removes need for hasClass, removeClass, addClass in favor of native classList.
`classList` works natively on all browsers, with a few exceptions for IE11 (of course): http://caniuse.com/#search=classList
Notes on using: https://developer.mozilla.org/en-US/docs/Web/API/Element/classList
Namely, it will not work on IE11 on SVG elements (not applicable for us) and `add` and `remove` will not support multiple parameters on IE11.  This why a few cases in this PR are multi-lined for those instances.

Refactor to remove dependencies on utils

---

src/manager.js
src/manager.spec.js

Enables Google Single request mode for The top banner, superhero (top&bottom), and welcome ad to be  requested at the same time. The result looks like the response below.
The corresponding PR to enable the functionality in kinja is here: 
https://github.com/gawkermedia/kinja-mantle/pull/12263
TODO: Due to the way this is designed, we'll need to check how the header bids are placed as key vals. Since they are added using setTargeting, the expectation is that DFP will wrap the keys within the individual ad calls.  However in the short term index is having issues appending key vals.  As such more validation will be required with index exchange.
see https://github.com/theonion/bulbs-public-ads-manager/pull/38

SRA for bulbs

---

src/helpers/Experiments.js
src/helpers/Experiments.spec.js

This PR will use `window.gaVariation` if it is set, and take priority of that over using `window.cxApi`
```
npm test
```

Allow window.gaVariation to be used and take priority if it is set

---

src/manager.js

What is this PR?
We were using `body.clientWidth`, however downstream we're calling `window.matchMedia()` which looks at `window.innerWidth`. This PR updates the width we want to examine and is consistent with what we will expect.
Also this bug fixes a production issue when your browser width is at 1024px - 1037px and the TOP_BANNER and LEFT_TOP ads do not show up as expected.

bug - use window.innerWidth

---

src/helpers/AdZone.js
src/helpers/AdZone.spec.js

**What is it:**
This PR is to update the function `getForcedAdZone()`. Based on conversations in slack and the requirements of the ticket, it was determined that we need to check the query string parameter of `adzone`.  
**Asana Ticket:**
https://app.asana.com/0/366985625403531/682105519698537/f

Fix (ads) Forced AdZone refactor

---

src/helpers/TargetingPairs.js
src/helpers/TargetingPairs.spec.js

This PR refactors the `getTargetingPairs()` to account for third party users of our library, such as Reductress.

Chore (ads) get targeting pair refactor

---

src/manager.js
src/manager.spec.js

Merge TARGETING global with targeting pairs instead of using one or the other, so forced ad zone can co-exist

Merge targeting global with targeting pairs logic

---

src/manager.js
src/manager.spec.js

Fixed an issue with a9 bidding not correctly being invoked for lazy-loaded ads, and also cleaned up the logic a bit as part of this update.  Note, instructions for how to test this PR (other than the unit test coverage here) are provided in the Mantle PR

Fixed an issue with a9 bidding

---

src/manager.js
src/manager.spec.js

Added logic to start sending 1-based (instead of starting at 0) index targeting to each of the ad calls on our pages.

Add ad position index targeting to each of the ad calls

---

src/manager.js
src/manager.spec.js

Fixes these errors I've started seeing periodically in Mantle:

Fix issue with A9 bids finishing and trying to set targeting before Index is ready

---

bower.json
package.json
src/ad-units.js
src/manager.js
src/manager.spec.js

Adds optional callback methods for `slotOnImpressionViewable`, `slotOnLoad` and `slotOnRefresh` to invoke when correlating event fires. 
Correlates with gawkermedia/kinja-mantle#16139

Ad performance tracking

---

package.json
src/manager.js

Mobile posts won't refresh if there are no active sizes

check for activeSizes in `refreshSlot`

---

src/helpers/TargetingPairs.js

missed this, and nowhere in our pipeline does it err until jenkins tries to build with it.
not worth adding checks to prevent this at this point since we're migrating this to mantle, which will let us bundle it like other js packages. so for now, just have to be more careful

refactor es6 syntax

---

src/helpers/TargetingPairs.js
src/helpers/TargetingPairs.spec.jest.js

last tiny fix, was returning `1` even when not in reading list (frontpage), don't think we want that.

fix article_position default val
